name: Build

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  restore:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore KerbalColoniesCore/source/KerbalColoniesCore.sln

  build:
    needs: restore
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main
